
-- =========================================================
-- ORGANIZACIÓN MAESTRA DE BASE DE DATOS - RADIO TIEMPO MUERTO
-- =========================================================
-- Instrucciones: Copia todo este contenido en el 'SQL Editor' de Supabase y presiona 'Run'.

-- 1. TABLA DE CHAT (Fogón Digital)
CREATE TABLE IF NOT EXISTS chat_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_name TEXT NOT NULL,         
  message TEXT,                    
  image_url JSONB DEFAULT '[]'::jsonb, 
  is_news BOOLEAN DEFAULT false,   
  status TEXT DEFAULT 'visible',   
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. TABLA DE PEDIDOS MUSICALES (Cabina / RadioBOSS)
CREATE TABLE IF NOT EXISTS song_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  song_title TEXT NOT NULL,        
  notes TEXT,                      
  status TEXT DEFAULT 'pending',   
  submission_mode TEXT,            
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. TABLA DE SALUDOS (Muro de la Comunidad)
CREATE TABLE IF NOT EXISTS radio_greetings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_name TEXT NOT NULL,
  location TEXT,                   
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. TABLA DE APORTES (Ticker de Donaciones)
CREATE TABLE IF NOT EXISTS contributions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_name TEXT NOT NULL,
  item_type TEXT NOT NULL,         
  amount NUMERIC NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. TABLA DE PODCASTS (Propuestas de Programas)
CREATE TABLE IF NOT EXISTS podcast_proposals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  topic TEXT,
  duration TEXT,                   
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. ESTADÍSTICAS GLOBALES (Contador de Mates)
CREATE TABLE IF NOT EXISTS global_stats (
  id TEXT PRIMARY KEY,             
  counter_value BIGINT DEFAULT 0,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
INSERT INTO global_stats (id, counter_value) VALUES ('mates_cebados', 0) ON CONFLICT (id) DO NOTHING;

-- 7. TABLA DE PUBLICIDAD (Nuevo Sistema Dinámico)
CREATE TABLE IF NOT EXISTS advertisements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slot TEXT DEFAULT 'top', -- 'top' o 'middle'
  title TEXT NOT NULL,
  subtitle TEXT,
  icon_key TEXT DEFAULT 'fa-bullhorn',
  image_url TEXT, -- Nuevo campo para póster
  target_url TEXT,
  owner_email TEXT,
  duration_days INT DEFAULT 7,
  status TEXT DEFAULT 'pending_payment', -- 'pending_payment', 'active', 'expired'
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. TABLA DE NOTICIAS URGENTES (Ticker Manual)
CREATE TABLE IF NOT EXISTS ticker_news (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content TEXT NOT NULL,
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =========================================================
-- 9. SEGURIDAD Y PERMISOS (Row Level Security - RLS)
-- =========================================================
ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE song_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE radio_greetings ENABLE ROW LEVEL SECURITY;
ALTER TABLE contributions ENABLE ROW LEVEL SECURITY;
ALTER TABLE podcast_proposals ENABLE ROW LEVEL SECURITY;
ALTER TABLE global_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE advertisements ENABLE ROW LEVEL SECURITY;
ALTER TABLE ticker_news ENABLE ROW LEVEL SECURITY;

-- Limpieza de policies antiguas
DROP POLICY IF EXISTS "Public Chat Access" ON chat_messages;
DROP POLICY IF EXISTS "Public Songs Access" ON song_requests;
DROP POLICY IF EXISTS "Public Greetings Access" ON radio_greetings;
DROP POLICY IF EXISTS "Public Contributions Access" ON contributions;
DROP POLICY IF EXISTS "Public Podcasts Access" ON podcast_proposals;
DROP POLICY IF EXISTS "Public Stats Access" ON global_stats;
DROP POLICY IF EXISTS "Public Ads Access" ON advertisements;
DROP POLICY IF EXISTS "Public Ticker Access" ON ticker_news;

-- Policies Públicas
CREATE POLICY "Public Chat Access" ON chat_messages FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Songs Access" ON song_requests FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Greetings Access" ON radio_greetings FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Contributions Access" ON contributions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Podcasts Access" ON podcast_proposals FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Stats Access" ON global_stats FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Ads Access" ON advertisements FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Ticker Access" ON ticker_news FOR ALL USING (true) WITH CHECK (true);

-- =========================================================
-- 10. ACTIVACIÓN DE REALTIME
-- =========================================================
ALTER PUBLICATION supabase_realtime ADD TABLE chat_messages;
ALTER PUBLICATION supabase_realtime ADD TABLE contributions;
ALTER PUBLICATION supabase_realtime ADD TABLE radio_greetings;
ALTER PUBLICATION supabase_realtime ADD TABLE global_stats;
ALTER PUBLICATION supabase_realtime ADD TABLE advertisements;
ALTER PUBLICATION supabase_realtime ADD TABLE ticker_news;
